android_library (
        name = "rewrite-lib",
        custom_package = "net.evendanan.rewrite_lib",
        manifest = "src/main/AndroidManifest.xml",
        resource_files = glob(["src/main/res/**"]),
        srcs = glob(["src/main/java/**/*.java"]),
        visibility = ["//visibility:public"],
)