android_library(
        name = "lib-with-resource",
        srcs = glob(["src/main/java/**/*.java"]),
        resource_files = glob(["src/main/res/**"]),
        custom_package = "net.evendanan.bazelplayground.libwithresource",
        manifest = "src/main/AndroidManifest.xml",
        deps = [],
        visibility = ["//visibility:public"]
)
