java_library(
    name = "javalib",
    srcs = glob(["src/main/java/**/*.java"]),
    deps = [],
    visibility = ["//visibility:public"],
    #removing this to allow lambdas
    #javacopts = ["-source 7", "-target 7"]
)