#java_toolchain(
#        name = "java_7_toolchain",
#        source_version = "7",
#        target_version = "7",
#        encoding = "UTF-8",
#)

java_library(
    name = "javalib",
    srcs = glob(["src/main/java/**/*.java"]),
    deps = [],
    visibility = ["//visibility:public"]
)